name: AssemblyInfo Version
author: Jason Davis
description: Get the version from AssemblyInfo files in older style Visual Studio projects 

inputs:
    AI_PATH:
        description: Filepath of the AssemblyInfo.cs file, relative to root of repository
        required: true
outputs:
    ASSEMBLY_VERSION:
        description: AssemblyVersion in the AssemblyInfo file
runs:
    using: node12
    main: index.js
    
branding:
    icon: activity
    color: gray-dark
    
