name: AssemblyInfo Version
author: Jason Davis
description: Get the version from AssemblyInfo files in older style Visual Studio projects 

inputs:
    AI_PATH:
        description: Filepath of the AssemblyInfo.cs file, relative to root of repository
        required: true
    VER_PLACES :
        description: Number of places of the version number to return (Major.Minor.Build.Revision). 1 for Major, 2 for Major.Minor, 3 for Major.Minor.Build, 4 for Major.Minor.Build.Revision.
        required: false

outputs:
    ASSEMBLY_VERSION:
        description: AssemblyVersion in the AssemblyInfo file
runs:
    using: node12
    main: index.js
    
branding:
    icon: activity
    color: gray-dark
