name: AssemblyInfo Version
author: Jason Davis
description: Get the version from AssemblyInfo files in older style Visual Studio projects 

inputs:
    AI_PATH:
        description: Filepath of the project to be packaged, relative to root of repository
        required: true
outputs:
    ASSEMBLY_VERSION:
        description: AssemblyVersion in the AssemblyInfo file
runs:
    using: node12
    main: index.js