name: "Test the action"
on:
  push:
    branches: [ master ]

jobs:
  
  test the action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        AI_PATH: ./github/workflows/AssemblyInfo.cs

